name: 'Deploy Infra'
description: 'Deploy CloudFormation stacks'

inputs:
  environment:
    description: 'Environment name (dev, stg, prod)'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: 'ap-northeast-1'
  stack-prefix:
    description: 'CloudFormation stack name prefix'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy App ECR Stack
      shell: bash
      run: |
        aws cloudformation deploy \
          --stack-name "${{ inputs.stack-prefix }}-ecr-app" \
          --template-file "cfn/templates/ecr-app.yaml" \
          --parameter-overrides "cfn/params/ecr-app.json"
