name: 'Deploy Infra'
description: 'Deploy CloudFormation stacks'

inputs:
  environment:
    description: 'Environment name (dev, stg, prod)'
    required: true
  aws-region:
    description: 'AWS region'
    required: true
    default: 'ap-northeast-1'
  stack-prefix:
    description: 'CloudFormation stack name prefix'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Deploy ECR Stack
      uses: aws-actions/aws-cloudformation-github-deploy@v1
      with:
        name: ${{ inputs.stack-prefix }}-ecr-app
        template: cfn/templates/ecr-app.yaml
        no-fail-on-empty-changeset: "1"
        parameter-overrides: "file:///${{ github.workspace }}/cfn/params/${{ inputs.environment }}/ecr-app.json"
