name: 'Build App'
description: 'Build App'

inputs:
  aws-account-id:
    description: 'AWS Account Id to push'
    required: true

  aws-region:
    description: 'AWS Region to push'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build
      uses: docker/build-push-action@v6
      with:
        push: true
        context: ./app
        tags: ${{ inputs.aws-account-id }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/ecr-test-repository:latest
