Parameters:
  Project:
    Type: String
  Environment:
    Type: String
    AllowedValues: [dev, stg, prod]
  ProdDeployRoleArn:
    Type: String
    NoEcho: true

Conditions:
  IsStgEnv: !Equals [ !Ref Environment, "stg" ]

Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Sub "${Project}-${Environment}-ecr-app"
      RepositoryPolicyText: !If
        - IsStgEnv
        - Version: "2012-10-17"
          Statement:
            - Sid: "AllowProdDeployRolePull"
              Effect: "Allow"
              Principal:
                AWS: !Ref ProdDeployRoleArn
              Action:
                - "ecr:GetDownloadUrlForLayer"
                - "ecr:BatchGetImage"
                - "ecr:BatchCheckLayerAvailability"
        - !Ref "AWS::NoValue"
